### PR TITLE
feat: update SampleTable to use Form fields to match parent field

### PR DESCRIPTION
**Pull request by frankie-mur**
## Description 
- This PR updates the SampleTable.tsx file to fix text styling and sizing, this addresses the issue #2470. 
- I was not able to test the `sample` button press and calling openAPI with loading data into the table as I do not have an paid openAPI key and it seems free plan does not support :( , should not effect this but if someone can confirm that would be appreciated
- I am very novice with React/Tailwind so please feel free to give tips and pointers where needed 
- Thanks 👍

### CODE REVIEW

**Comment by nickzelei** [comment]
Hi @frankie-mur ! 
Appreciate the PR.

Do you think it would be possible to update this component to use similar styles without using the Form components directly? This table isn't a part of the form itself so I would prefer if it did not use the form components.

**Comment by frankie-mur** [comment]
Thanks for the review @nickzelei , I have updated much simpler and without using Form components

**Comment by evisdrenova** [comment]
@frankie-mur here is the styling for the subtext for the other form fields, we'll just want them to look the same. 

```js
const FormDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => {
  const { formDescriptionId } = useFormField();

  return (
    <p
      ref={ref}
      id={formDescriptionId}
      className={cn('text-[0.8rem] text-muted-foreground', className)}
      {...props}
    />
  );
});
FormDescription.displayName = 'FormDescription';
```

**Comment by frankie-mur** [comment]
Appreciate that @evisdrenova, should we also update the heading `Synthetic Data Sample` to match the other form fields?

**Comment by nickzelei** [comment]
> Appreciate that @evisdrenova, should we also update the heading `Synthetic Data Sample` to match the other form fields? Also since we don't want use Form components directly would it be appropriate to use the same className attributes directly? ex.
> 
> ```
>      <p className="text-[0.8rem] text-muted-foreground tracking-tight">
>             A sample of synthetic data given the inputs above. Returns at most
>             10 records.
>      </p>
> ```

Yep it is totally appropriate to use the same class names! These are just tailwind classes so it's totally fine to use those as they are used for rendering purposes.

We could update the heading, however, it's not intended to stand out as it's a separate part of the form.
However, if it looks better uniform with the others, I'm down for it!

**Comment by frankie-mur** [comment]
image

**Pull request merged**
