### PR TITLE
Nic/doc fixes

### PR DESCRIPTION
**Pull request by NicHaley**
Some spelling fixes for the `deploy` directory. I used an AI linter to catch these

### CODE REVIEW

**Review by nickzelei — APPROVED** [review]
Thank you for fixing this!

Something I've been thinking about for a while (that I've used in the past) is turning on https://github.com/DavidAnson/markdownlint in some capacity.
I've used it indirectly before with the `super-linter` project.

But just using markdownlint on MD files could be really useful in catching stuff like this more generally.

**Comment by nickzelei** [comment]
Logged ticket for adding md lint #1093

**Comment by nickzelei** [comment]
@NicHaley looks like the prettier workflow failed. Can you run prettier on the docs folder and have it fix what it finds? Should be able to run `npm run prettier:write` from within the docs repo.

**Comment by NicHaley** [comment]
> @NicHaley looks like the prettier workflow failed. Can you run prettier on the docs folder and have it fix what it finds? Should be able to run `npm run prettier:write` from within the docs repo.

@nickzelei Ran that and pushed. lmk if that solved it!

**Pull request merged**
